name: ShopSystem
version: 0.1
authors: [Leon167, LekoHD]
description: Official ShopSystem Plugin
main: com.lekohd.shopsystem.ShopSystem

commands:
  shop:
    aliases: [sh, sp]
    description: Place or remove a Shop
    usage: /shop place/remove - place/remove a shop on your position
